{{- if not .Values.config.existingConfigMap }}
{{- if not .Values.config.files }}
{{- fail "Either config.existingConfigMap or config.files must be set." }}
{{- end }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "shadowtraffic.fullname" . }}-config
  labels:
    {{- include "shadowtraffic.labels" . | nindent 4 }}
data:
  {{- range $filename, $content := .Values.config.files }}
  {{ $filename }}: |
    {{- $content | nindent 4 }}
  {{- end }}
{{- end }}
