{{- if not .Values.license.existingSecret }}
{{- if not .Values.license.inline.id }}
{{- fail "Either license.existingSecret or license.inline.id (plus edition, expiration, signature) must be set." }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "shadowtraffic.fullname" . }}-license
  labels:
    {{- include "shadowtraffic.labels" . | nindent 4 }}
stringData:
  LICENSE_EDITION: {{ .Values.license.inline.edition | quote }}
  LICENSE_ID: {{ .Values.license.inline.id | quote }}
  LICENSE_EMAIL: {{ .Values.license.inline.email | quote }}
  LICENSE_ORGANIZATION: {{ .Values.license.inline.organization | quote }}
  LICENSE_EXPIRATION: {{ .Values.license.inline.expiration | quote }}
  LICENSE_SIGNATURE: {{ .Values.license.inline.signature | quote }}
{{- end }}
