apiVersion: v1
kind: Service
metadata:
  name: {{ include "shadowtraffic.fullname" . }}
  labels:
    {{- include "shadowtraffic.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "shadowtraffic.selectorLabels" . | nindent 4 }}
  ports:
    - name: metrics
      port: {{ .Values.service.metricsPort }}
      targetPort: metrics
      protocol: TCP
    {{- if .Values.studio.enabled }}
    - name: studio
      port: {{ .Values.service.studioPort }}
      targetPort: studio
      protocol: TCP
    {{- end }}
